#!/bin/bash

DARK_MODE_STATUS_FILE=~/.cache/dark-mode
CURRENT_DARK_MODE=$( cat $DARK_MODE_STATUS_FILE )

LIGHT="盛"
DARK=""

if [ "$1" == "--toggle" ]; then
  if [ $CURRENT_DARK_MODE == "light" ]; then
    ~/.config/waybar/scripts/set-theme dark
  else
    ~/.config/waybar/scripts/set-theme light
  fi
fi

if [ $CURRENT_DARK_MODE != "light" ]; then
  echo $DARK
else
  echo $LIGHT
fi
