#!/bin/bash

reply_action () {

  echo "Eyyy"

}
forward_action () {
  echo "Sup"
}
handle_dismiss () {
  echo "Dismiss"
}

ACTION=$(dunstify --action="default,Reply" --action="forwardAction,Forward" "Message Received")

case "$ACTION" in
"default")
    reply_action
    ;;
"forwardAction")
    forward_action
    ;;
"2")
    handle_dismiss
    ;;
esac
