lastupdatecheck: 0
recentrepos:
- /home/max/.dotfiles
- /home/max/Projects/silvester
- /home/max/Projects/ruumio/main
- /home/max/Projects/ruumio/feat-3d-poi
- /home/max/Projects/ruumio
- /home/max/Projects/gainz
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
